### ISSUE TITLE
Uploading video file issue

### ISSUE THREAD

**Issue by madebyiando** [stevewithington/MuraPlayer#2]
Hi

When trying to upload a video file (37mb) the operation appears to time out and goes to a blank screen. I assumed this may because the hosting company has a restriction on upload size but I thought an error message may have displayed, have you seen this before? My clients host is murahosting.com.

Cheers

Shaun

**Comment by stevewithington** [comment]
Well, the default POST limitation in Adobe CF is 20 MB. Also, I think the default timeout request is 60 seconds...so it could be a combination of these, or any number of other issues. For example, most Windows servers have a cap on form post data as well. I saw your request on MuraHosting.com and will see what our settings are there.

I'm going to close this issue here since it's not a bug though. Thanks!
